// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodingActivity: typeof import('./src/components/codingActivity.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Durations: typeof import('./src/components/durations.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LanguagesPie: typeof import('./src/components/languagesPie.vue')['default']
    ProjectTime: typeof import('./src/components/projectTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
